### ISSUE TITLE
Error on JOIN between commit_files and ref_commits

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#37]
Executing the following query:
```scala
spark.sql("""SELECT
    file_path,
    ref_commits.repository_id
FROM
    commit_files
NATURAL JOIN
    ref_commits
WHERE
    ref_commits.ref_name = 'HEAD'
    AND ref_commits.history_index = 0""")
```

I get the following error: 

```
Name: org.apache.spark.sql.AnalysisException
Message: cannot resolve '`ref_commits.repository_id`' given input columns: [commit_files.repository_id, ref_commits.ref_name, commit_files.tree_hash, ref_commits.history_index, commit_files.file_path, commit_files.commit_hash, commit_files.blob_hash]; line 3 pos 4;
'Project [file_path#52, 'ref_commits.repository_id]
+- Filter ((ref_name#10 = HEAD) && (history_index#11L = cast(0 as bigint)))
   +- Project [repository_id#50, commit_hash#51, file_path#52, blob_hash#53, tree_hash#54, ref_name#10, history_index#11L]
      +- Join Inner, ((repository_id#50 = repository_id#8) && (commit_hash#51 = commit_hash#9))
         :- SubqueryAlias commit_files
         :  +- DataSourceV2Relation [repository_id#50, commit_hash#51, file_path#52, blob_hash#53, tree_hash#54], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(file_path,StringType,true), StructField(blob_hash,StringType,true), StructField(tree_hash,StringType,true)),Table(commit_files))
         +- SubqueryAlias ref_commits
            +- DataSourceV2Relation [repository_id#8, commit_hash#9, ref_name#10, history_index#11L], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(ref_name,StringType,true), StructField(history_index,LongType,true)),Table(ref_commits))

StackTrace:   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:92)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:89)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:106)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:118)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$1.apply(QueryPlan.scala:122)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:122)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:127)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:127)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:89)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:84)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:84)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:92)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:74)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
```

**Comment by ajnavarro** [comment]
It is happening with more queries, and appears to be the same error:
```sql
select
    files.file_path,
    ref_commits.repository_id,
    files.blob_content
FROM
    files
NATURAL JOIN
    commit_files
NATURAL JOIN
    ref_commits
WHERE
    ref_commits.ref_name = 'HEAD'
    AND ref_commits.history_index BETWEEN 0 AND 5
    AND is_binary(blob_content) = false
    AND files.file_path NOT REGEXP '^vendor.*'
    AND (
        blob_content REGEXP '(?i)facebook.*[\'\\"][0-9a-f]{32}[\'\\"]'
        OR blob_content REGEXP '(?i)twitter.*[\'\\"][0-9a-zA-Z]{35,44}[\'\\"]'
        OR blob_content REGEXP '(?i)github.*[\'\\"][0-9a-zA-Z]{35,40}[\'\\"]'
        OR blob_content REGEXP 'AKIA[0-9A-Z]{16}'
        OR blob_content REGEXP '(?i)reddit.*[\'\\"][0-9a-zA-Z]{14}[\'\\"]'
        OR blob_content REGEXP '(?i)heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'
        OR blob_content REGEXP '.*-----BEGIN PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN RSA PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN DSA PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN OPENSSH PRIVATE KEY-----.*'
    )
```

```
Name: org.apache.spark.sql.AnalysisException
Message: cannot resolve '`ref_commits.repository_id`' given input columns: [ref_commits.ref_name, files.repository_id, files.blob_hash, ref_commits.history_index, files.file_path, files.blob_content, files.blob_size, commit_files.commit_hash, files.tree_entry_mode, files.tree_hash]; line 3 pos 4;
'Project [file_path#79, 'ref_commits.repository_id, blob_content#83]
+- Filter ((((ref_name#10 = HEAD) && ((history_index#11L >= cast(0 as bigint)) && (history_index#11L <= cast(5 as bigint)))) && (UDF:is_binary(cast(blob_content#83 as binary)) = false)) && (NOT file_path#79 RLIKE ^vendor.* && ((((blob_content#83 RLIKE (?i)facebook.*['\"][0-9a-f]{32}['\"] || blob_content#83 RLIKE (?i)twitter.*['\"][0-9a-zA-Z]{35,44}['\"]) || blob_content#83 RLIKE (?i)github.*['\"][0-9a-zA-Z]{35,40}['\"]) || (blob_content#83 RLIKE AKIA[0-9A-Z]{16} || blob_content#83 RLIKE (?i)reddit.*['\"][0-9a-zA-Z]{14}['\"])) || (((blob_content#83 RLIKE (?i)heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12} || blob_content#83 RLIKE .*-----BEGIN PRIVATE KEY-----.*) || blob_content#83 RLIKE .*-----BEGIN RSA PRIVATE KEY-----.*) || (blob_content#83 RLIKE .*-----BEGIN DSA PRIVATE KEY-----.* || blob_content#83 RLIKE .*-----BEGIN OPENSSH PRIVATE KEY-----.*)))))
   +- Project [repository_id#78, commit_hash#51, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L, ref_name#10, history_index#11L]
      +- Join Inner, ((repository_id#78 = repository_id#8) && (commit_hash#51 = commit_hash#9))
         :- Project [repository_id#78, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L, commit_hash#51]
         :  +- Join Inner, ((((repository_id#78 = repository_id#50) && (file_path#79 = file_path#52)) && (blob_hash#80 = blob_hash#53)) && (tree_hash#81 = tree_hash#54))
         :     :- SubqueryAlias files
         :     :  +- DataSourceV2Relation [repository_id#78, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(file_path,StringType,true), StructField(blob_hash,StringType,true), StructField(tree_hash,StringType,true), StructField(tree_entry_mode,StringType,true), StructField(blob_content,StringType,true), StructField(blob_size,LongType,true)),Table(files))
         :     +- SubqueryAlias commit_files
         :        +- DataSourceV2Relation [repository_id#50, commit_hash#51, file_path#52, blob_hash#53, tree_hash#54], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(file_path,StringType,true), StructField(blob_hash,StringType,true), StructField(tree_hash,StringType,true)),Table(commit_files))
         +- SubqueryAlias ref_commits
            +- DataSourceV2Relation [repository_id#8, commit_hash#9, ref_name#10, history_index#11L], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(ref_name,StringType,true), StructField(history_index,LongType,true)),Table(ref_commits))

StackTrace: 'Project [file_path#79, 'ref_commits.repository_id, blob_content#83]
+- Filter ((((ref_name#10 = HEAD) && ((history_index#11L >= cast(0 as bigint)) && (history_index#11L <= cast(5 as bigint)))) && (UDF:is_binary(cast(blob_content#83 as binary)) = false)) && (NOT file_path#79 RLIKE ^vendor.* && ((((blob_content#83 RLIKE (?i)facebook.*['\"][0-9a-f]{32}['\"] || blob_content#83 RLIKE (?i)twitter.*['\"][0-9a-zA-Z]{35,44}['\"]) || blob_content#83 RLIKE (?i)github.*['\"][0-9a-zA-Z]{35,40}['\"]) || (blob_content#83 RLIKE AKIA[0-9A-Z]{16} || blob_content#83 RLIKE (?i)reddit.*['\"][0-9a-zA-Z]{14}['\"])) || (((blob_content#83 RLIKE (?i)heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12} || blob_content#83 RLIKE .*-----BEGIN PRIVATE KEY-----.*) || blob_content#83 RLIKE .*-----BEGIN RSA PRIVATE KEY-----.*) || (blob_content#83 RLIKE .*-----BEGIN DSA PRIVATE KEY-----.* || blob_content#83 RLIKE .*-----BEGIN OPENSSH PRIVATE KEY-----.*)))))
   +- Project [repository_id#78, commit_hash#51, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L, ref_name#10, history_index#11L]
      +- Join Inner, ((repository_id#78 = repository_id#8) && (commit_hash#51 = commit_hash#9))
         :- Project [repository_id#78, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L, commit_hash#51]
         :  +- Join Inner, ((((repository_id#78 = repository_id#50) && (file_path#79 = file_path#52)) && (blob_hash#80 = blob_hash#53)) && (tree_hash#81 = tree_hash#54))
         :     :- SubqueryAlias files
         :     :  +- DataSourceV2Relation [repository_id#78, file_path#79, blob_hash#80, tree_hash#81, tree_entry_mode#82, blob_content#83, blob_size#84L], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(file_path,StringType,true), StructField(blob_hash,StringType,true), StructField(tree_hash,StringType,true), StructField(tree_entry_mode,StringType,true), StructField(blob_content,StringType,true), StructField(blob_size,LongType,true)),Table(files))
         :     +- SubqueryAlias commit_files
         :        +- DataSourceV2Relation [repository_id#50, commit_hash#51, file_path#52, blob_hash#53, tree_hash#54], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(file_path,StringType,true), StructField(blob_hash,StringType,true), StructField(tree_hash,StringType,true)),Table(commit_files))
         +- SubqueryAlias ref_commits
            +- DataSourceV2Relation [repository_id#8, commit_hash#9, ref_name#10, history_index#11L], DefaultReader(WrappedArray(GitbaseServer(gitbase,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(ref_name,StringType,true), StructField(history_index,LongType,true)),Table(ref_commits))
  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:92)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:89)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:107)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:106)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:118)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$1.apply(QueryPlan.scala:122)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:122)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:127)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:127)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:95)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:89)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:84)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:84)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:92)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:74)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
```

**Comment by ajnavarro** [comment]
My fault, projected `repository_id` columns on spark are coming for other tables
